### ISSUE TITLE
broiler.exe requires visual studio 2013 x86 redistributable package

### ISSUE THREAD

**Issue by Janzert** [bugdone/packrat#1]
Specifically when trying to run broiler.exe I get a system error pop up with "The program can't start because MSVCP120.dll is missing from your computer. Try reinstalling the program to fix this problem."

This is a dll from the VS2013 redistributable package and can be downloaded from https://www.microsoft.com/en-us/download/details.aspx?id=40784 (note that even with an x64 system the x86 package is needed) or if I recall correctly if you have the properly licensed version of VS2013 it could also be included with the release.

**Comment by bugdone** [comment]
Thanks, I updated the readme mentioning it as a dependency.
