### ISSUE TITLE
Error fetching links

### ISSUE THREAD

**Issue by wadum** [bugdone/packrat#3]
After the last update to cs:go packrat is no longer able to fetch the replays. Is it a problem on my end, or does it affect others too ?

The output of broiler seems to be a list with empty strings, and the .dem.info names miss some of their information, eg. : match730_000000000000000000000_1522700636_186.dem.info (It shouldn't be all zeroes, the correct name is match730_003085506051634626621_1522700636_186.dem.info

**Comment by bugdone** [comment]
Thanks for reporting this.
It seems in the latest release some protobufs were changed.

**Comment by wadum** [comment]
:ok_hand:
